// Ported from the prototype (resource_management_v2.html). Demo "today" is 2026-09-08.
// Not app code: only prisma/seed.ts imports this.

export interface SeedAlloc {
  code: string;
  pct: number;
  billable: boolean;
  start: string;
  end: string;
}
export interface SeedPerson {
  id: string;
  name: string;
  role: string;
  band: string;
  team: string;
  loc: string;
  tz: string;
  hours: number;
  verifier: string;
  skills: string[];
  status: string;
  allocs: SeedAlloc[];
  benchSince?: string;
}

export const DEMO_TODAY = '2026-09-08';

export const NAMED_PEOPLE: SeedPerson[] = [
  {
    id: 'e1',
    name: 'Anita Raghavan',
    role: 'Senior developer',
    band: 'B4',
    team: 'Platform engineering',
    loc: 'Bengaluru',
    tz: 'IST (UTC+5:30)',
    hours: 8,
    verifier: 'M. Feld',
    skills: ['Java', 'Spring', 'AWS'],
    allocs: [
      {
        code: 'P-101',
        pct: 100,
        billable: true,
        start: '2026-06-01',
        end: '2027-03-31',
      },
    ],
    status: 'Allocated',
  },
  {
    id: 'e2',
    name: 'Marcus Feld',
    role: 'Architect',
    band: 'B6',
    team: 'Platform engineering',
    loc: 'Berlin',
    tz: 'CET (UTC+1)',
    hours: 8,
    verifier: 'Practice lead',
    skills: ['Java', 'Kafka', 'AWS'],
    allocs: [
      {
        code: 'P-101',
        pct: 50,
        billable: true,
        start: '2026-06-01',
        end: '2027-03-31',
      },
      {
        code: 'P-103',
        pct: 30,
        billable: false,
        start: '2026-05-04',
        end: '2026-12-18',
      },
    ],
    status: 'Allocated',
  },
  {
    id: 'e3',
    name: 'Priya Nair',
    role: 'QA lead',
    band: 'B4',
    team: 'Quality engineering',
    loc: 'Kochi',
    tz: 'IST (UTC+5:30)',
    hours: 8,
    verifier: 'M. Kulkarni',
    skills: ['Cypress', 'API testing', 'Selenium'],
    allocs: [
      {
        code: 'P-103',
        pct: 50,
        billable: true,
        start: '2026-05-04',
        end: '2026-12-18',
      },
    ],
    status: 'Allocated',
  },
  {
    id: 'e4',
    name: 'Tomás Oliveira',
    role: 'Developer',
    band: 'B3',
    team: 'Digital product',
    loc: 'Lisbon',
    tz: 'WET (UTC+0)',
    hours: 8,
    verifier: 'C. Bertrand',
    skills: ['React', 'TypeScript', 'Node'],
    allocs: [
      {
        code: 'P-104',
        pct: 60,
        billable: true,
        start: '2026-08-03',
        end: '2027-02-27',
      },
      {
        code: 'P-102',
        pct: 40,
        billable: true,
        start: '2026-09-15',
        end: '2027-06-30',
      },
    ],
    status: 'Allocated',
  },
  {
    id: 'e5',
    name: 'Dae-jung Park',
    role: 'Developer',
    band: 'B3',
    team: 'Digital product',
    loc: 'Seoul',
    tz: 'KST (UTC+9)',
    hours: 8,
    verifier: 'C. Bertrand',
    skills: ['React', 'GraphQL', 'Node'],
    allocs: [],
    status: 'Locked-Tentative',
  },
  {
    id: 'e6',
    name: 'Ingrid Solberg',
    role: 'Data engineer',
    band: 'B5',
    team: 'Data and analytics',
    loc: 'Oslo',
    tz: 'CET (UTC+1)',
    hours: 8,
    verifier: 'Practice lead',
    skills: ['Python', 'Spark', 'Snowflake'],
    allocs: [],
    benchSince: '2026-08-18',
    status: 'Bench',
  },
  {
    id: 'e7',
    name: 'Rahul Mehta',
    role: 'Developer',
    band: 'B2',
    team: 'Platform engineering',
    loc: 'Pune',
    tz: 'IST (UTC+5:30)',
    hours: 8,
    verifier: 'A. Raghavan',
    skills: ['Java', 'React'],
    allocs: [],
    status: 'Available',
  },
  {
    id: 'e8',
    name: 'Chloe Bertrand',
    role: 'UX engineer',
    band: 'B4',
    team: 'Digital product',
    loc: 'Lyon',
    tz: 'CET (UTC+1)',
    hours: 8,
    verifier: 'Practice lead',
    skills: ['React', 'CSS', 'Design systems'],
    allocs: [
      {
        code: 'P-104',
        pct: 100,
        billable: true,
        start: '2026-08-03',
        end: '2027-02-27',
      },
    ],
    status: 'Allocated',
  },
  {
    id: 'e9',
    name: 'Samuel Osei',
    role: 'DevOps engineer',
    band: 'B5',
    team: 'Platform engineering',
    loc: 'Accra',
    tz: 'GMT (UTC+0)',
    hours: 8,
    verifier: 'M. Feld',
    skills: ['AWS', 'Terraform', 'Kubernetes'],
    allocs: [
      {
        code: 'P-101',
        pct: 60,
        billable: true,
        start: '2026-07-01',
        end: '2027-01-31',
      },
    ],
    status: 'Allocated',
  },
  {
    id: 'e10',
    name: 'Yuki Tanaka',
    role: 'QA engineer',
    band: 'B2',
    team: 'Quality engineering',
    loc: 'Osaka',
    tz: 'JST (UTC+9)',
    hours: 8,
    verifier: 'P. Nair',
    skills: ['Cypress', 'Playwright'],
    allocs: [],
    status: 'On Leave',
  },
  {
    id: 'e11',
    name: 'Diego Ramírez',
    role: 'Developer',
    band: 'B4',
    team: 'Digital product',
    loc: 'Bogotá',
    tz: 'COT (UTC-5)',
    hours: 8,
    verifier: 'M. Kulkarni',
    skills: ['Node', 'AWS', 'Postgres'],
    allocs: [],
    benchSince: '2026-08-30',
    status: 'Bench',
  },
  {
    id: 'e12',
    name: 'Fatima Al-Habib',
    role: 'Architect',
    band: 'B6',
    team: 'Platform engineering',
    loc: 'Dubai',
    tz: 'GST (UTC+4)',
    hours: 8,
    verifier: 'Practice lead',
    skills: ['Azure', '.NET', 'Kubernetes'],
    allocs: [],
    status: 'Locked-Confirmed',
  },
];

export const PROJECTS = [
  {
    code: 'P-101',
    name: 'Northwind core migration',
    client: 'Northwind Retail',
    priority: 'High',
    start: '2026-06-01',
    end: '2027-03-31',
    phase: 'In flight',
    lead: 'S. Whitlock',
    effort: '3,840 h',
    effortUsed: '2,610 h',
    billable: '92%',
    skills: ['Java', 'AWS', 'Kafka'],
    need: 8,
    filled: 6,
    demand: [
      {
        role: 'Senior developer',
        skills: 'Java, Spring',
        need: 4,
        filled: 3,
      },
      {
        role: 'DevOps engineer',
        skills: 'AWS, Terraform',
        need: 2,
        filled: 2,
      },
      {
        role: 'QA engineer',
        skills: 'API testing',
        need: 2,
        filled: 1,
      },
    ],
  },
  {
    code: 'P-102',
    name: 'Helios analytics platform',
    client: 'Meridian Energy',
    priority: 'High',
    start: '2026-09-15',
    end: '2027-06-30',
    phase: 'Mobilising',
    lead: 'J. Adeyemi',
    effort: '5,120 h',
    effortUsed: '740 h',
    billable: '100%',
    skills: ['Python', 'Spark', 'React'],
    need: 5,
    filled: 2,
    demand: [
      {
        role: 'Data engineer',
        skills: 'Python, Spark',
        need: 3,
        filled: 1,
      },
      {
        role: 'Developer',
        skills: 'React, TypeScript',
        need: 2,
        filled: 1,
      },
    ],
  },
  {
    code: 'P-103',
    name: 'Atlas payments rewrite',
    client: 'Cascade Bank',
    priority: 'Medium',
    start: '2026-05-04',
    end: '2026-12-18',
    phase: 'In flight, closing December',
    lead: 'S. Whitlock',
    effort: '2,960 h',
    effortUsed: '2,410 h',
    billable: '88%',
    skills: ['Java', 'Node', 'Cypress'],
    need: 6,
    filled: 6,
    demand: [
      {
        role: 'Developer',
        skills: 'Java',
        need: 3,
        filled: 3,
      },
      {
        role: 'Developer',
        skills: 'Node, Postgres',
        need: 2,
        filled: 2,
      },
      {
        role: 'QA lead',
        skills: 'Cypress',
        need: 1,
        filled: 1,
      },
    ],
  },
  {
    code: 'P-104',
    name: 'Vector mobile refresh',
    client: 'Kestrel Media',
    priority: 'Low',
    start: '2026-08-03',
    end: '2027-02-27',
    phase: 'In flight',
    lead: 'R. Osment',
    effort: '1,880 h',
    effortUsed: '620 h',
    billable: '75%',
    skills: ['React', 'CSS', 'Playwright'],
    need: 4,
    filled: 2,
    demand: [
      {
        role: 'Developer',
        skills: 'React',
        need: 3,
        filled: 2,
      },
      {
        role: 'QA engineer',
        skills: 'Playwright',
        need: 1,
        filled: 0,
      },
    ],
  },
  {
    code: 'P-105',
    name: 'Orion data warehouse',
    client: 'Northwind Retail',
    priority: 'Medium',
    start: '2026-11-02',
    end: '2027-08-31',
    phase: 'Pipeline, not started',
    lead: 'J. Adeyemi',
    effort: '4,200 h',
    effortUsed: '0 h',
    billable: '100%',
    skills: ['Python', 'Snowflake'],
    need: 3,
    filled: 0,
    demand: [
      {
        role: 'Data engineer',
        skills: 'Python, Snowflake',
        need: 2,
        filled: 0,
      },
      {
        role: 'Architect',
        skills: 'Azure, data',
        need: 1,
        filled: 0,
      },
    ],
  },
];

export const HOLIDAYS = [
  {
    date: '2026-10-02',
    name: 'Gandhi Jayanti',
    region: 'India',
  },
  {
    date: '2026-10-03',
    name: 'Foundation Day',
    region: 'South Korea',
  },
  {
    date: '2026-10-26',
    name: 'National Day',
    region: 'Europe',
  },
  {
    date: '2026-11-03',
    name: 'Culture Day',
    region: 'Japan',
  },
  {
    date: '2026-12-25',
    name: 'Christmas Day',
    region: 'All regions',
  },
];

export const LEAVE = [
  {
    id: 'l1',
    emp: 'e10',
    type: 'Parental leave',
    from: '2026-08-03',
    to: '2026-11-02',
    status: 'Approved',
  },
  {
    id: 'l2',
    emp: 'e4',
    type: 'Annual leave',
    from: '2026-10-02',
    to: '2026-10-03',
    status: 'Approved',
  },
  {
    id: 'l3',
    emp: 'e8',
    type: 'Annual leave',
    from: '2026-10-26',
    to: '2026-10-29',
    status: 'Pending',
  },
  {
    id: 'l4',
    emp: 'e9',
    type: 'Sick leave',
    from: '2026-10-14',
    to: '2026-10-15',
    status: 'Pending',
  },
  {
    id: 'l5',
    emp: 'e1',
    type: 'Annual leave',
    from: '2026-11-12',
    to: '2026-11-14',
    status: 'Approved',
  },
  {
    id: 'l6',
    emp: 'e2',
    type: 'Annual leave',
    from: '2026-12-21',
    to: '2026-12-25',
    status: 'Pending',
  },
];

export const SKILL_REQS = [
  {
    id: 's1',
    emp: 'e7',
    skill: 'Terraform',
    status: 'Pending',
  },
  {
    id: 's2',
    emp: 'e11',
    skill: 'Kubernetes',
    status: 'Pending',
  },
];

export const RULES = [
  {
    id: 'r1',
    event: 'Over-allocation attempted',
    trigger: 'Any save that would exceed 100%',
    audience: 'Resource manager, delivery manager',
    on: true,
    channel: 'In app and email',
    frequency: 'Immediately',
  },
  {
    id: 'r2',
    event: 'Bench threshold passed',
    trigger: 'Unallocated longer than the threshold',
    audience: 'Resource manager, practice lead',
    on: true,
    channel: 'In app and email',
    frequency: 'Daily digest',
  },
  {
    id: 'r3',
    event: 'Lock about to expire',
    trigger: '7 days before a tentative lock expires',
    audience: 'Resource manager',
    on: true,
    channel: 'In app only',
    frequency: 'Daily digest',
  },
  {
    id: 'r4',
    event: 'Release approaching',
    trigger: '14 days before an allocation ends',
    audience: 'Delivery manager',
    on: true,
    channel: 'Email only',
    frequency: 'Weekly digest',
  },
  {
    id: 'r5',
    event: 'Skill gap on a demand line',
    trigger: 'Open line with no matching candidate',
    audience: 'Practice lead, leadership',
    on: false,
    channel: 'Email only',
    frequency: 'Weekly digest',
  },
  {
    id: 'r6',
    event: 'Leave request raised',
    trigger: 'A new request overlapping an allocation',
    audience: 'Resource manager',
    on: true,
    channel: 'In app and email',
    frequency: 'Immediately',
  },
];

export const SAVED_REPORTS = [
  {
    name: 'Quarterly utilization by team',
    type: 'Utilization',
    scope: 'Utilization, all teams, rolling quarter',
    schedule: 'Monthly to leadership',
  },
  {
    name: 'Bench and open demand',
    type: 'Allocation',
    scope: 'Allocation, all teams, next 60 days',
    schedule: 'Weekly to practice leads',
  },
  {
    name: 'Northwind staffing audit',
    type: 'Allocation',
    scope: 'Allocation, Platform engineering, year to date',
    schedule: null,
  },
];
